# Generated by Django 4.2.1 on 2023-05-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(verbose_name='долгота')),
                ('latitude', models.FloatField(verbose_name='широта')),
                ('height', models.IntegerField(verbose_name='высота')),
            ],
        ),
        migrations.CreateModel(
            name='Uzers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='эл.почта')),
                ('cell', models.IntegerField(help_text='в формате 7903ххххххх', unique=True, verbose_name='сотовый')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'в работе'), ('accepted', 'принят'), ('rejected', 'отклонён')], default='new', verbose_name='статус модерации')),
                ('beautyTitle', models.CharField(max_length=200, verbose_name='beautyTitle')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('other_titles', models.CharField(max_length=200, verbose_name='other_titles')),
                ('connectother_titles', models.CharField(blank=True, max_length=200, verbose_name='соединяет')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('level_winter', models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], verbose_name='зима')),
                ('level_summer', models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], verbose_name='лето')),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passag.coords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passag.uzers')),
            ],
        ),
        migrations.CreateModel(
            name='pereval_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_photo', models.CharField(max_length=20, verbose_name='описание фото')),
                ('img', models.URLField(verbose_name='ссылка на фото')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passag.perevaladded')),
            ],
        ),
    ]
