# Generated by Django 4.2.1 on 2023-05-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0002_alter_perevaladded_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval_images',
            name='pereval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='passag.perevaladded'),
        ),
    ]
