# Generated by Django 4.2.1 on 2023-05-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0004_alter_perevaladded_level_summer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='beautyTitle',
            field=models.CharField(max_length=200, verbose_name='тип объекта'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='connectother_titles',
            field=models.CharField(blank=True, max_length=200, verbose_name='что соединяет'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='other_titles',
            field=models.CharField(max_length=200, verbose_name='альтернативное название'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='title',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
    ]
