# Generated by Django 4.2.1 on 2023-05-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0005_alter_perevaladded_beautytitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_1', models.CharField(max_length=100, verbose_name='описание фото_1')),
                ('pic_1', models.URLField(verbose_name='ссылка на фото_1')),
                ('about_2', models.CharField(blank=True, max_length=100, verbose_name='описание фото_2')),
                ('pic_2', models.URLField(blank=True, verbose_name='ссылка на фото_3')),
                ('about_3', models.CharField(blank=True, max_length=100, verbose_name='описание фото_3')),
                ('pic_3', models.URLField(blank=True, verbose_name='ссылка на фото_3')),
            ],
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='images',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='passag.img'),
            preserve_default=False,
        ),
    ]
