# Generated by Django 4.2.1 on 2023-05-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0006_img_perevaladded_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pereval_images',
        ),
    ]
