# Generated by Django 4.2.1 on 2023-05-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0007_delete_pereval_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passag.coords', verbose_name='Координаты'),
        ),
    ]
