# Generated by Django 4.2.1 on 2023-05-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0008_alter_perevaladded_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_1', models.CharField(max_length=100, verbose_name='описание фото_1')),
                ('pic_1', models.URLField(verbose_name='ссылка на фото_1')),
                ('about_2', models.CharField(blank=True, max_length=100, verbose_name='описание фото_2')),
                ('pic_2', models.URLField(blank=True, verbose_name='ссылка на фото_3')),
                ('about_3', models.CharField(blank=True, max_length=100, verbose_name='описание фото_3')),
                ('pic_3', models.URLField(blank=True, verbose_name='ссылка на фото_3')),
            ],
        ),
        migrations.RenameField(
            model_name='perevaladded',
            old_name='connectother_titles',
            new_name='connect_other_titles',
        ),
        migrations.RemoveField(
            model_name='img',
            name='about_2',
        ),
        migrations.RemoveField(
            model_name='img',
            name='about_3',
        ),
        migrations.RemoveField(
            model_name='img',
            name='pic_2',
        ),
        migrations.RemoveField(
            model_name='img',
            name='pic_3',
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='images',
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xyz', to='passag.coords', verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='images',
            field=models.ManyToManyField(to='passag.img'),
        ),
    ]
