# Generated by Django 4.2.1 on 2023-05-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0009_imgold_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgOld',
        ),
        migrations.AddField(
            model_name='img',
            name='about_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='описание фото_2'),
        ),
        migrations.AddField(
            model_name='img',
            name='about_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='описание фото_3'),
        ),
        migrations.AddField(
            model_name='img',
            name='pic_2',
            field=models.URLField(blank=True, verbose_name='ссылка на фото_3'),
        ),
        migrations.AddField(
            model_name='img',
            name='pic_3',
            field=models.URLField(blank=True, verbose_name='ссылка на фото_3'),
        ),
        migrations.RemoveField(
            model_name='perevaladded',
            name='images',
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='images',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='passag.img'),
            preserve_default=False,
        ),
    ]
