# Generated by Django 4.2.1 on 2023-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0010_delete_imgold_img_about_2_img_about_3_img_pic_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='about_1',
            field=models.CharField(help_text='обязательное поле', max_length=100, verbose_name='описание фото_1'),
        ),
        migrations.AlterField(
            model_name='img',
            name='pic_1',
            field=models.URLField(help_text='обязательное поле', verbose_name='ссылка на фото_1'),
        ),
        migrations.AlterField(
            model_name='img',
            name='pic_2',
            field=models.URLField(blank=True, verbose_name='ссылка на фото_2'),
        ),
    ]
