# Generated by Django 4.2.1 on 2023-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0016_alter_perevaladded_level_summer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('pending', 'в работе'), ('accepted', 'принят'), ('rejected', 'отклонён')], default='pending', verbose_name='статус модерации'),
        ),
    ]
