# Generated by Django 4.2.1 on 2023-06-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0021_alter_perevaladded_level_summer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='level_summer',
            field=models.CharField(blank=True, choices=[('', 'не указано'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], null=True, verbose_name='лето'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='level_winter',
            field=models.CharField(blank=True, choices=[('', 'не указано'), ('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('4a', '4А'), ('4b', '4Б'), ('5a', '5А'), ('5b', '5Б'), ('6a', '6А'), ('6b', '6Б')], null=True, verbose_name='зима'),
        ),
    ]
