# Generated by Django 4.2.1 on 2023-06-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0022_alter_perevaladded_level_summer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coords',
            name='height',
            field=models.IntegerField(help_text='обязательное поле', verbose_name='высота'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='latitude',
            field=models.FloatField(help_text='обязательное поле', verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='coords',
            name='longitude',
            field=models.FloatField(help_text='обязательное поле', verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='img',
            name='pic_1',
            field=models.URLField(help_text='обязательное поле, url фото', verbose_name='ссылка на фото_1'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='beautyTitle',
            field=models.CharField(help_text='обязательное поле', max_length=200, verbose_name='тип объекта'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='other_titles',
            field=models.CharField(help_text='обязательное поле', max_length=200, verbose_name='альтернативное название'),
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='title',
            field=models.CharField(help_text='обязательное поле', max_length=200, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='uzers',
            name='cell',
            field=models.IntegerField(help_text='обязательное поле в формате 7903ххххххх', verbose_name='сотовый'),
        ),
        migrations.AlterField(
            model_name='uzers',
            name='email',
            field=models.EmailField(help_text='обязательное поле', max_length=50, unique=True, verbose_name='эл.почта'),
        ),
        migrations.AlterField(
            model_name='uzers',
            name='family',
            field=models.CharField(help_text='обязательное поле', max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='uzers',
            name='name',
            field=models.CharField(help_text='обязательное поле', max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='uzers',
            name='patronymic',
            field=models.CharField(help_text='обязательное поле', max_length=20, verbose_name='Отчество'),
        ),
    ]
