# Generated by Django 4.2.1 on 2023-06-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passag', '0025_alter_perevaladded_level_summer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzers',
            name='cell',
            field=models.BigIntegerField(help_text='обязательное поле в формате 7903ххххххх', verbose_name='сотовый'),
        ),
    ]
